apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: delfiatech/harness-delfia-public:latest
        ports:
        - containerPort: 80
      tolerations:
      - key: luiz
        operator: Equal
        value: delivery
        effect: NoSchedule
